export default

[
  {
    "_id": "Q1",
    "name": "Cyber Security Quiz",
    "course": "CS2550",
    "title": "Cyber Security Quiz",
    "description": "Test your knowledge of cyber security!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "QC1",
    "name": "Cyber Security Quiz2 ADDED",
    "course": "CS2550",
    
    "title": "Cyber Security Quiz2",
    "description": "Test your knowledge of cyber security!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "QC2",
    "name": "Cyber Security Quiz3 ADDED",
    "course": "CS2550",
    
    "title": "Cyber Security Quiz3",
    "description": "Test your knowledge of cyber security!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q2",
    "name": "Co-Op Quiz",
    "course": "CS1210",
    "title": "Co-Op Quiz",
    "description": "Test your knowledge of co-operative education!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q3",
    "name": "WebDev Quiz",
    "course": "CS4550",
    "title": "WebDev Quiz",
    "description": "Test your knowledge of web development!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q4",
    "name": "Computer Systems Quiz",
    "course": "CS3650",
    "title": "Computer Systems Quiz",
    "description": "Test your knowledge of computer systems!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q5",
    "name": "ReactJS Quiz",
    "course": "RS106",
    "title": "ReactJS Quiz",
    "description": "Test your knowledge of ReactJS!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q6",
    "name": "Theory Quiz",
    "course": "CS3800",
    "title": "Theory Quiz",
    "description": "Test your knowledge of theory!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q7",
    "name": "Rocket Propulsion Quiz",
    "course": "RS101",
    "title": "Rocket Propulsion Quiz",
    "description": "Test your knowledge of rocket propulsion!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q8",
    "name": "Aerodynamics Quiz",
    "course": "RS102",
    "title": "Aerodynamics Quiz",
    "description": "Test your knowledge of aerodynamics!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  },
  {
    "_id": "Q9",
    "name": "Spacecraft Design Quiz",
    "course": "RS103",
    "title": "Spacecraft Design Quiz",
    "description": "Test your knowledge of spacecraft design!",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2023-05-15T23:59:59Z",
    "availableDate": "2023-01-10T00:00:00Z",
    "untilDate": "2023-05-15T23:59:59Z"
  }
]


  